public enum GameScreenType
{
    None = 0,
    MenuMain = 1,
    Death = 2,
    Pause = 3,
    HUD = 4,
    Loading = 5,
    Options = 6,
    LoadGame = 7,
    Leaderboard = 8,
    SelectGameMode = 9,
    NewGame = 10,
    KeyBindings = 11,
    AudioSettings = 12,
    AboutGame = 13,
    Collectibles = 14,
    Items = 15,
    Enemies = 16,
    Consumables = 17,
    Misc = 18,
    Tutorials = 19,
    ReplayTutorial = 20,
}
